### ISSUE TITLE
Re-run scraper job to get completed results

### ISSUE THREAD

**Issue by Abundnce10** [Prooffreader/election_2016_data#2]
Hi,

First off, thanks for compiling all of this information!  

I was looking through the `presidential_general_election_2016_by_county` file and noticed there are still 507 counties that aren't reported at 100% -- the majority are from Utah and Washington. 

Is there any way you could run your script again to scrape the results?  I'm assuming all states/counties are reporting at 100% now.  That way we'd have an entirely clear view into the total number of votes for each county.

**Comment by Prooffreader** [comment]
Thanks for the kind words, I've rerun the script. There are more counties at higher % reporting now, but not everyone is at 100% yet.

I've also added a ``change_tracking`` folder to easily see what has changed between each update.
