### ISSUE TITLE
data description

### ISSUE THREAD

**Issue by Y4m1n** [Prooffreader/election_2016_data#3]
Could you please add some details to the data in the readme file? I have trouble understanding the meaning of each columns. Thanks a lot!

**Comment by Prooffreader** [comment]
I've added a data dictionary for the columns I scraped from Politico. Note that if you're wondering about the columns in the ``merged_with_demog`` folder, you'll have to inquire with the repo I got it from, https://github.com/Deleetdk/USA.county.data
